#!/usr/bin/env bash

icons=("" "" "")
date="$HOME/.cache/eww/osd_brightness.date"

osd() {
	if [ ! -f "$date" ]; then
		mkdir -p "$HOME/.cache/eww"
	fi
	date +%s >"$date"
}

osd_handler() {
	lock=0
	rundate=0
	if [ ! -f "$date" ]; then
		mkdir -p "$HOME/.cache/eww"
		echo 0 >"$date"
	fi

	while true; do
		# get dates
		rundate=$(cat "$date")
		currentdate=$(date +%s)

		# handle showing
		if [ "$rundate" = "$currentdate" ] && [ "$lock" -eq 0 ]; then
            "$(dirname "$0")"/toggle_window osd_brightness open
			lock=1
		elif [ "$((currentdate - rundate))" = "2" ] && [ "$lock" -eq 1 ]; then
            "$(dirname "$0")"/toggle_window osd_brightness close
			lock=0
		fi

		sleep 0.5
	done

    "$(dirname "$0")"/toggle_window osd_brightness close
}

if [ "$1" = "osd" ]; then
	osd
else
	osd_handler &
	# initial
	icon=${icons[$(awk -v n="$(light)" 'BEGIN{print int(n/34)}')]}
	echo '{ "percent": '"$(light)"', "icon": "'"$icon"'" }'

	udevadm monitor | rg --line-buffered "backlight" | while read -r _; do
		icon="${icons[$(awk -v n="$(light)" 'BEGIN{print int(n/34)}')]}"

		echo '{ "percent": '"$(light)"', "icon": "'"$icon"'" }'
	done
fi
