#!/bin/sh

time="$(date "+%k" | awk '{$1=$1};1')00"
date="$(date "+%Y-%m-%d")"
curl -s 'wttr.in?format=j1' | jq "[.weather[] | {date, hourly: .hourly[]} | {date, temp: .hourly.tempC, time: .hourly.time, weatherCode: .hourly.weatherCode, chanceofrain: .hourly.chanceofrain, precipMM: .hourly.precipMM} | select((.date | startswith(\"$date\") | not) or ((.time | tonumber) >= $time))]" | sed -E 's|([0-9]{4})-([0-9]{2})-([0-9]{2})|\3/\2|g'
