#!/bin/sh

check_lives () {
	while read -r id symbol
    do
        name="$(echo "$id" | sed 's/\([^[:blank:]]\)\([[:upper:]]\)/\1 \2/g')"
        curl -s "https://www.youtube.com/@$id" | grep -q "hqdefault_live.jpg" && printf "{\"id\": \"%s\", \"icon\": \"%s\", \"name\": \"%s\"}," "$id" "$symbol" "$name"
	done
}

input () {
	echo "KureijiOllie 🧟"
	echo "MoonaHoshinova 🌕"

	echo "GawrGura 🔱"
    echo "WatsonAmelia 🔎"
    echo "MoriCalliope 💀"
    echo "TakanashiKiara 🐔"
    echo "NinomaeInanis 🐙"

    echo "IRyS 💎"

    # echo "UCsUj0dszADCGbF3gNrQEuSQ 🪐" :'(
    echo "CeresFauna 🌿"
    echo "NanashiMumei 🪶 "
    echo "OuroKronii ⏳"
    echo "HakosBaelz 🎲"
}

text="$(input | check_lives)"
if [ -n "$text" ]; then
    echo "[${text%?}]"
else
    echo "[]"
fi
