#!/bin/sh

check_lives () {
	while read -r id symbol
    do
        if [ "$id" = "IRyS" ] || [ "$id" = "AZKi" ]; then
            name="$id"
        else
            name="$(echo "$id" | sed 's/\([^[:blank:]]\)\([[:upper:]]\)/\1 \2/g')"
        fi

        curl -s "https://www.youtube.com/@$id" | grep -q "hqdefault_live.jpg" && printf "{\"id\": \"%s\", \"icon\": \"%s\", \"name\": \"%s\"}," "$id" "$symbol" "$name"
	done
}

input () {
    echo "TokinoSora 🐻"
    echo "Robocosan 🤖"
    echo "AZKi 💿"
    echo "SakuraMiko 🌸"
    echo "HoshimachiSuisei ☄️"

    echo "YozoraMel 🌟"
    echo "AkiRosenthal 🍎"
    echo "AkaiHaato ❤️"
    echo "ShirakamiFubuki 🦊"
    echo "NatsuiroMatsuri 🏮"

    echo "MinatoAqua ⚓️"
    echo "MurasakiShion 🌙"
    echo "NakiriAyame 😈"
    echo "YuzukiChoco 💋"
    echo "OozoraSubaru 🪿"

    echo "OokamiMio 🐺"
    echo "NekomataOkayu 🐱"
    echo "InugamiKorone 🐶"

    echo "UsadaPekora 🥕"
    echo "ShiranuiFlare 🔥"
    echo "ShiroganeNoel ⚔️"
    echo "HoushouMarine ☠️"

    echo "AmaneKanata 💫"
    echo "TsunomakiWatame 🐏"
    echo "TokoyamiTowa 👾"
    echo "HimemoriLuna 🍬"
    # echo "KiryuCoco 🐉" :(

    echo "YukihanaLamy ☃️"
    echo "MomosuzuNene 🍑"
    echo "ShishiroBotan ♌"
    echo "OmaruPolka 🎪"

    echo "LaplusDarknesss 🛸"
    echo "TakaneLui 🥀"
    echo "HakuiKoyori 🧪"
    echo "SakamataChloe 🎣"
    echo "KazamaIroha 🍃"

	echo "KureijiOllie 🧟"
	echo "MoonaHoshinova 🌕"
    echo "AyundaRisu 🐿"
    echo "AiraniIofifteen 🎨"
    echo "AnyaMelfissa 🍂"
    echo "PavoliaReine 🦚"
    echo "VestiaZeta 📜"
    echo "KaelaKovalskia 🔨"
    echo "KoboKanaeru ☔"

	echo "GawrGura 🔱"
    echo "WatsonAmelia 🔎"
    echo "MoriCalliope 💀"
    echo "TakanashiKiara 🐔"
    echo "NinomaeInanis 🐙"

    echo "IRyS 💎"

    # echo "UCsUj0dszADCGbF3gNrQEuSQ 🪐" :'(
    echo "CeresFauna 🌿"
    echo "NanashiMumei 🪶 "
    echo "OuroKronii ⏳"
    echo "HakosBaelz 🎲"
}

text="$(input | check_lives)"
if [ -n "$text" ]; then
    echo "[${text%?}]"
else
    echo "[]"
fi
