#!/bin/sh

NUM_MONITORS="$(hyprctl monitors | grep -c "Monitor")"
current_mon="$(cat "/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/active_monitor")"

window="$1"
action="$2"

[ "$NUM_MONITORS" -gt 1 ] && window="$1_dual$(( current_mon + 1 ))"

if [ -z "$action" ]; then
    eww open --toggle "$window"
else
    eww "$action" "$window"
fi
