#!/bin/sh

NUM_MONITORS="$(hyprctl monitors | grep -c "Monitor")"
current_mon="$(hyprctl -j monitors | jaq '.[]? | select(.focused == true) | .id')"

window="$1"
action="$2"

[ "$NUM_MONITORS" -gt 1 ] && window="$1_dual$(( current_mon + 1 ))"

if [ -z "$action" ]; then
    closer="$1-closer_dual$(( current_mon + 1 ))"

    eww close "$closer"
    eww open --toggle "$closer"
    eww open --toggle "$window"
else
    eww "$action" "$window"
fi
