#!/bin/sh

monitor_id="$1"
monitor="$(hyprctl -j monitors | jaq -r ".[] | select(.id == $monitor_id) | .name")"

color_empty="#313244"
color_normal="#666666"
color_focused="#eeeeee"

icon_normal=""
icon_focused=""

# generate the json for eww
generate() {
	seq 1 10 | while read -r ws; do
		[ -f "/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/active_monitor" ] && ws="$((monitor_id + 1))$(printf "%s" "$ws" | tail -c 1)"

        if [ "$ws" = "$(get_focusedws)" ]; then
			color="$color_focused"
			icon="$icon_focused"
		elif hyprctl clients | grep -q "workspace: $ws"; then
			color="$color_normal"
			icon="$icon_normal"
		else
			color="$color_empty"
			icon="$icon_normal"
		fi

		printf "{ \"number\": \"%s\", \"icon\": \"%s\", \"color\": \"%s\" }," "$ws" "$icon" "$color"
	done | format_json
}

format_json() {
	output="$(cat)"
	echo "[${output%?}]"
}

get_focusedws() {
	hyprctl -j monitors | jaq -r ".[] | select(.id == $monitor_id) | .activeWorkspace.id"
}

# generate initial widget
generate

# main loop
socat -u UNIX-CONNECT:/tmp/hypr/"$HYPRLAND_INSTANCE_SIGNATURE"/.socket2.sock - | rg --line-buffered "workspace|mon(itor)?" | while read -r line; do
	case "${line%>>*}" in
	"workspace")
        generate
		;;
	esac
done
