---
- name: Install AMD packages from pacman
  when: amd.stdout != ""
  become: true
  community.general.pacman:
    name:
      - vulkan-radeon
      - lib32-vulkan-radeon
      - mesa
      - libva-mesa-driver
      - lib32-libva-mesa-driver
      - radeontop
    state: present

- name: Install AMD packages from AUR
  when: amd.stdout != ""
  become: true
  become_user: aur_builder
  kewlfft.aur.aur:
    name:
      - amdgpu_top
      - amdguid-wayland-bin
    state: present
