---
- name: Install audio packages
  become: true
  community.general.pacman:
    name:
      - alsa-firmware
      - alsa-utils
      - wireplumber
      - pipewire-pulse
      - pamixer
      - pavucontrol
    state: present

- name: Enable pipewire systemctl service
  systemd:
    name: pipewire
    enabled: true
    scope: user

- name: Enable wireplumber systemctl service
  systemd:
    name: wireplumber
    enabled: true
    scope: user
