---
- name: Install pacman packages
  become: true
  community.general.pacman:
    name:
      - archlinux-keyring
      - linux-headers
      - lsb-release
      - man-db
      - os-prober
      - moreutils
      - mtpfs
      - ntfs-3g
      - v4l2loopback-dkms
      - virtualbox-host-modules-arch
      - openssh
      - usbutils
      - vim
      - htop
      - parted
      - neofetch
      - fastfetch
      - btop
      - eza
      - zip
      - ffmpeg
      - playerctl
      - tldr
      - openvpn
      - uwufetch
      - magic-wormhole
      - ncspot
      - ncdu
      - android-file-transfer
      - valgrind
      - jdk-openjdk
      - jupyter-notebook
      - rkhunter
      - bluez
      - bluez-utils
      - pacman-contrib
      - libva
      - libva-utils
      - nvtop
      - tree
      - yt-dlp
      - light
      - bitwarden
      - inotify-tools
    state: present
- name: Install AUR packages
  become: true
  become_user: aur_builder
  kewlfft.aur.aur:
    name:
      - networkmanager-iwd
      - cava
      - python-pip
      - python-bibtexparser
      - python-inkscape-figures
      - python-undetected-chromedriver
      - peerflix
    state: present

- name: Remove network conflicts
  become: true
  community.general.pacman:
    name:
      - networkmanager
      - libnm
    state: absent

- name: Create .config/btop/themes directory
  file:
    path: "{{ ansible_env.HOME }}/.config/btop/themes"
    state: directory

- name: Install makefile2graph
  become: true
  make:
    chdir: "{{ ansible_env.HOME }}/.config/setup/programs/makefile2graph"

- name: Add v4l2loopback module
  become: true
  lineinfile:
    path: /etc/modules-load.d/v4l2loopback.conf
    line: "v4l2loopback"
    create: true

- name: Enable bluetooth systemd service
  become: true
  systemd:
    name: bluetooth
    enabled: true
