---
- name: Delete aur_builder user
  become: true
  user:
    name: aur_builder
    state: absent
    remove: true

- name: Remove sudoers.d file
  become: true
  file:
    path: /etc/sudoers.d/11-install-aur_builder
    state: absent
