---
- name: Install docker
  become: true
  community.general.pacman:
    name:
      - docker
      - docker-compose
    state: present

- name: Enable docker service
  become: true
  systemd:
    name: docker
    enabled: true

- name: Create docker group
  become: true
  group:
    name: docker
    state: present

- name: Add user to docker group
  become: true
  user:
    name: "{{ ansible_env.USER }}"
    groups:
      - docker
    append: true
