---
- name: Check for dotfiles
  stat:
    path: "{{ ansible_env.HOME }}/.config/.dotfiles-git/HEAD"
  register: dotfiles_head

- name: Clone dotfiles repository
  git:
    accept_hostkey: true
    repo: git@github.com:Vinschers/dotfiles.git
    dest: "{{ ansible_env.HOME }}/.config/.dotfiles-git"
    bare: true
  when: not dotfiles_head.stat.exists

- name: Install dotfiles
  shell: |
    git --git-dir="{{ ansible_env.HOME }}/.config/.dotfiles-git/" --work-tree="{{ ansible_env.HOME }}" checkout 2>&1 | grep -E "\s+\." | awk '{print $1}' | xargs -I{} rm "$HOME/{}"
    git --git-dir="{{ ansible_env.HOME }}/.config/.dotfiles-git/" --work-tree="{{ ansible_env.HOME }}" checkout
    git --git-dir="{{ ansible_env.HOME }}/.config/.dotfiles-git/" --work-tree="{{ ansible_env.HOME }}" config --local status.showUntrackedFiles no
