---
- name: Install eww dependencies
  become: true
  community.general.pacman:
    name:
      - bc
    state: present

- name: Install eww
  become: true
  become_user: aur_builder
  kewlfft.aur.aur:
    name: eww-wayland
    state: present
