---
- name: Install firejail
  become: true
  community.general.pacman:
    name: firejail
    state: present

- name: Setup firejail
  become: true
  block:
    - name: Disable chafa
      lineinfile:
        path: /etc/firejail/firecfg.config
        regexp: 'chafa'
        line: '#chafa'
    - name: Disable man
      lineinfile:
        path: /etc/firejail/firecfg.config
        regexp: 'man'
        line: '#man'
    - name: Disable zathura
      lineinfile:
        path: /etc/firejail/firecfg.config
        regexp: 'zathura'
        line: '#zathura'
    - name: Run firecfg
      shell: firecfg
