---
- name: Create user groups
  become: true
  group:
    name: "{{ item }}"
    state: present
  loop: "{{ user_groups }}"
- name: Add user to groups
  become: true
  user:
    name: "{{ ansible_env.USER }}"
    groups: "{{ item }}"
    append: true
  loop: "{{ user_groups }}"
