---
- name: Install GUI programs from pacman
  become: true
  community.general.pacman:
    name:
      - keepassxc
      - mpv
      - imv
      - qbittorrent
      - discord
      - blueberry
      - network-manager-applet
      - gparted
      - mousepad
      - simple-scan
      - virtualbox
      - xournalpp
      - obs-studio
      - libreoffice-still
      - d-feet
      - gimp
      - zathura
      - zathura-pdf-mupdf
      - speech-dispatcher
      - thunar
      - tumbler
      - wf-recorder
    state: present

- name: Install GUI programs from AUR
  become: true
  become_user: aur_builder
  kewlfft.aur.aur:
    name:
      - librewolf-bin
      - iwgtk
      - sioyek
      - spotify
      - streamlink-twitch-gui-bin
      - selectdefaultapplication-git
    state: present

- name: Add user to virtualbox groups
  become: true
  user:
    name: "{{ ansible_env.USER }}"
    groups:
      - vboxusers
      - video
    append: true
