---
- name: Install Hyprland dependencies from pacman
  become: true
  community.general.pacman:
    name:
      - socat
      - qt5ct
      - qt5-wayland
      - qt6
      - kvantum
      - xdg-desktop-portal-hyprland
      - dunst
      - polkit-kde-agent
      - foot
      - wofi
      - slurp
      - grim
      - wl-clipboard
      - waylock
      - cpio
      - jq
      - cmake
    state: present

- name: Remove xdg-desktop-portal-gnome
  become: true
  community.general.pacman:
    name: xdg-desktop-portal-gnome
    state: absent

- name: Install Hyprland dependencies from AUR
  become: true
  become_user: aur_builder
  kewlfft.aur.aur:
    name:
      - wlogout
      - swww
      - wl-color-picker
      - nwg-look
      - spotifywm-git
      - wlrobs-hg
      - hyprsome-git
    state: present

- name: Install Hyprland with NVIDIA patch
  become: true
  become_user: aur_builder
  kewlfft.aur.aur:
    name: hyprland-nvidia
    state: present
  when: nvidia.stdout != ""

- name: Install Hyprland
  become: true
  community.general.pacman:
    name: hyprland
    state: present
  when: nvidia.stdout == ""
