---
- name: Install Hyprland dependencies from pacman
  become: true
  community.general.pacman:
    name:
      - socat
      - qt5ct
      - qt5-wayland
      - qt6
      - xdg-desktop-portal-wlr
      - dunst
      - polkit-kde-agent
      - foot
      - waybar
      - wofi
      - slurp
      - grim
      - wl-clipboard
      - waylock
      - cpio
      - jq
    state: present

- name: Install Hyprland dependencies from AUR
  become: true
  become_user: aur_builder
  kewlfft.aur.aur:
    name:
      - wlogout
      - swww
      - wl-color-picker
      - nwg-look
    state: present

- name: Install Hyprland
  become: true
  become_user: aur_builder
  kewlfft.aur.aur:
    name: hyprland
    state: present
