---
- name: Install Hyprland dependencies from pacman
  become: true
  community.general.pacman:
    name:
      - socat
      - qt5ct
      - qt5-wayland
      - qt6
      - xdg-desktop-portal-wlr
      - dunst
      - polkit-kde-agent
      - foot
      - waybar
      - wofi
      - slurp
      - grim
      - wl-clipboard
      - waylock
      - cpio
      - jq
    state: present

- name: Install Hyprland dependencies from AUR
  become: true
  become_user: aur_builder
  kewlfft.aur.aur:
    name:
      - wlogout
      - swww
      - wl-color-picker
      - nwg-look
    state: present

- name: Install Hyprland with NVIDIA patch
  become: true
  become_user: aur_builder
  kewlfft.aur.aur:
    name: hyprland-nvidia
    state: present
  when: nvidia.stdout != ""

- name: Install Hyprland
  become: true
  become_user: aur_builder
  kewlfft.aur.aur:
    name: hyprland
    state: present
  when: nvidia.stdout == ""

- name: Extract themes
  unarchive:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/.local/share/themes"
  loop:
    - "{{ ansible_env.HOME }}/.local/share/themes/Tokyonight-Dark-B.zip"
    - "{{ ansible_env.HOME }}/.local/share/themes/Catppuccin-Mocha-B.zip"
    - "{{ ansible_env.HOME }}/.local/share/themes/Nordic-darker.tar.xz"

- name: Extract theme icons
  unarchive:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/.local/share/icons"
  loop:
    - "{{ ansible_env.HOME }}/.local/share/icons/TokyoNight-SE.tar.bz2"
    - "{{ ansible_env.HOME }}/.local/share/icons/Catppuccin-Mocha.zip"
    - "{{ ansible_env.HOME }}/.local/share/icons/Zafiro-Nord-Black.tar.xz"
