---
- name: Install Rust
  become: true
  community.general.pacman:
    name:
      - rustup
    state: present

- name: Run rustup in current user
  shell: rustup default stable

# - name: Install jaq
#   become: true
#   become_user: aur_builder
#   block:
#     - name: Run rustup
#       shell: rustup default stable
#     - name: Install jaq from AUR
#       kewlfft.aur.aur:
#         name: jaq
#         state: present
