---
- name: Install Rust
  become: true
  community.general.pacman:
    name:
      - rustup
    state: present
  register: install_rust

- name: Setup Rust
  shell: rustup default stable
  when: install_rust.changed

- name: Install jaq
  become: true
  become_user: aur_builder
  kewlfft.aur.aur:
    name: jaq
    state: present
