---
- name: Install lf dependencies
  become: true
  community.general.pacman:
    name:
      - unrar
      - unzip
      - glow
      - atool
      - bat
      - gnome-epub-thumbnailer
      - mediainfo
      - lynx
      - odt2txt
      - pdf2svg
      - chafa
      - ffmpegthumbnailer
      - imagemagick
      - imlib2
      - libsixel
      - libxcrypt-compat
    state: present

- name: Setup Imagemagick
  lineinfile:
    path: /etc/ImageMagick-7/policy.xml
    regexp: 'name="memory"'
    line: '  <policy domain="resource" name="memory" value="2GiB"/>'

- name: Load bat themes
  shell: bat cache --build

- name: Install lf
  become: true
  become_user: aur_builder
  kewlfft.aur.aur:
    name: lf-sixel-git
    state: present
