---
- name: Check for Intel CPU
  shell: cat /proc/cpuinfo | { grep -i intel || true; }
  register: intel

- name: Check for NVIDIA GPU
  shell: lspci -k | grep -A 2 -E "(VGA|3D)" | { grep -i nvidia || true; }
  register: nvidia

- name: Check for AMD GPU
  shell: lspci -k | grep -A 2 -E "(VGA|3D)" | { grep -i amd || true; }
  register: amd

- import_tasks: grub.yml
- import_tasks: groups.yml
- import_tasks: pacman.yml
- import_tasks: aur.yml

- import_tasks: hardware.yml
- import_tasks: packages.yml
- import_tasks: systemd.yml

- import_tasks: git.yml
- import_tasks: sddm.yml

- import_tasks: filesystem.yml
