---
- name: Install neovim dependencies
  become: true
  community.general.pacman:
    name:
      - ripgrep
      - python-pynvim
      - lazygit
    state: present

- name: Install language servers
  become: true
  block:
    - name: LSP from pacman
      community.general.pacman:
        name:
          - bash-language-server
          - lua-language-server
          - typescript-language-server
          - pyright
          - yaml-language-server
          - clang
          - ansible-language-server
          - texlab
        state: present
    - name: LSP from AUR
      become: true
      become_user: aur_builder
      kewlfft.aur.aur:
        name:
          - nodejs-emmet-ls
          - dockerfile-language-server
          - jdtls
        state: present

- name: Install formatters and linters
  become: true
  block:
    - name: Formatters and linters from pacman
      community.general.pacman:
        name:
          - prettier
          - python-black
          - python-isort
          - stylua
          - shfmt
          - texlive-binextra
          - flake8
          - shellcheck
          - yamllint
          - eslint_d
        state: present
    - name: Formatters and linters from AUR
      become: true
      become_user: aur_builder
      kewlfft.aur.aur:
        name:
          - clang-format-all-git
          - google-java-format
          - asmfmt
          - proselint
          - bibclean
        state: present

- name: Install debug adapters
  become: true
  ignore_errors: true
  block:
    - name: Debug adapters from pacman
      community.general.pacman:
        name:
          - lldb
          - python-debugpy
        state: present
    - name: Debug adapters from AUR
      become: true
      become_user: aur_builder
      kewlfft.aur.aur:
        name:
          - bashdb
          - vscode-langservers-extracted
          - vscode-node-debug2
        state: present

- name: Install java-debug
  block:
    - name: Clone java-debug repository
      git:
        repo: https://github.com/microsoft/java-debug.git
        dest: "{{ ansible_env.HOME }}/.local/share/java-debug"
      register: java_debug
    - name: Install java-debug
      shell: "cd {{ ansible_env.HOME }}/.local/share/java-debug && ./mvnw clean install"
      when: java_debug.changed

- name: Install vscode-java-test
  block:
    - name: Clone vscode-java-test repository
      git:
        repo: https://github.com/microsoft/vscode-java-test.git
        dest: "{{ ansible_env.HOME }}/.local/share/java-test"
      register: java_test
    - name: Install java-test
      shell: "cd {{ ansible_env.HOME }}/.local/share/java-test && npm install && npm run build-plugin"
      when: java_test.changed

- name: Install neovim
  become: true
  community.general.pacman:
    name: neovim
    state: present

- name: Install "neovim" node.js package globally.
  become: true
  npm:
    name: neovim
    global: true
