---
- name: Check for NVIDIA GPU
  shell: lspci -k | grep -A 2 -E "(VGA|3D)" | { grep -i nvidia || true; }
  register: nvidia

- name: Install NVIDIA packages from pacman
  when: nvidia.stdout != ""
  become: true
  community.general.pacman:
    name:
      - nvidia-dkms
      - libva
      - libva-utils
      - nvidia-settings
      - nvidia-utils
      - opencl-nvidia
    state: present

- name: Install NVIDIA packages from AUR
  when: nvidia.stdout != ""
  become: true
  become_user: aur_builder
  kewlfft.aur.aur:
    name:
      - libva-nvidia-driver
    state: present

- name: Check if nvidia is configured in the boot command
  when: nvidia.stdout != ""
  lineinfile:
    backup: true
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT=".*nvidia_drm.modeset=1'
    state: absent
  check_mode: true
  register: grub_cmdline_check
  changed_when: false

- name: Insert nvidia_drm.modeset=1 if missing
  become: true
  block:
    - name: Update /etc/default/grub
      lineinfile:
        backrefs: true
        path: /etc/default/grub
        regexp: "^(GRUB_CMDLINE_LINUX_DEFAULT=\".*)\"$"
        line: '\1 nvidia_drm.modeset=1"'
    - name: Run grub-mkconfig
      shell: grub-mkconfig -o /boot/grub/grub.cfg
  when: nvidia.stdout != "" and grub_cmdline_check.found == 0

- name: Check if nvidia is configured in then kernel parameters
  when: nvidia.stdout != ""
  lineinfile:
    backup: true
    path: /etc/mkinitcpio.conf
    regexp: '^MODULES=\(.*nvidia nvidia_modeset nvidia_uvm nvidia_drm'
    state: absent
  check_mode: true
  register: mkinitcpio_cmdline_check
  changed_when: false

- name: Insert nvidia_drm.modeset=1 if missing
  become: true
  block:
    - name: Update mkinitcpio
      lineinfile:
        backrefs: true
        path: /etc/mkinitcpio.conf
        regexp: '^(MODULES=\(.*)\)$'
        line: '\1 nvidia nvidia_modeset nvidia_uvm nvidia_drm)'
    - name: Run mkinitcpio
      shell: mkinitcpio --config /etc/mkinitcpio.conf --generate /boot/initramfs-custom.img
  when: nvidia.stdout != "" and mkinitcpio_cmdline_check.found == 0

- name: Create /etc/modprobe.d/nvidia.conf
  when: nvidia.stdout != ""
  become: true
  lineinfile:
    path: /etc/modprobe.d/nvidia.conf
    line: 'options nvidia-drm modeset=1'
    create: true
