---
- name: Setup SSD Trim
  become: true
  systemd:
    name: "{{ item }}"
    enabled: true
  loop:
    - fstrim.timer
    - fstrim.service
  when: ssd_trim == "" or ssd_trim == "Y" or ssd_trim == "y"
