---
- name: Install ufw
  become: true
  block:
    - name: Download ufw
      community.general.pacman:
        name: ufw
        state: present
    - name: Set ufw default deny
      shell: ufw default deny
