---
- name: Install Zotero Translation Server
  ignore_errors: true
  become: true
  become_user: aur_builder
  kewlfft.aur.aur:
    name: zotero-translation-server-git
    state: present

- name: Enable Zotero Translation Server service
  ignore_errors: true
  become: true
  systemd:
    name: zotero-translation-server
    enabled: true
