---
- name: Install zsh
  become: true
  community.general.pacman:
    name:
      - starship
      - zsh
      - zsh-completions
    state: present

- name: Create .local/state/zsh directory
  file:
    path: "{{ ansible_env.HOME }}/.local/state/zsh"
    state: directory

- name: Install zsh plugins
  shell: ". {{ ansible_env.HOME }}/.config/zsh/.zshrc"

- name: Change shell to zsh
  become: true
  user:
    name: "{{ ansible_env.USER }}"
    shell: /bin/zsh
