#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi


sys_type="$(cat /sys/class/dmi/id/chassis_type)"

if [ "$sys_type" -eq 3 ] # Desktop
then
    echo "Desktop"
elif [ "$sys_type" -eq 10 ] # Notebook
then
    echo "Notebook"

    nm-applet &
else
    echo "Unknown system"
fi

xrandr --setprovideroutputsource modesetting NVIDIA-0
xrandr --auto


picom -f &
nitrogen --restore &
# xautolock -time $LOCK_TIME -locker lock -corners +00- &

exec dwm
