#!/bin/sh

. sb-style
STYLE="foreground"

n=2
logfile="${XDG_CACHE_HOME:-$HOME/.cache}/datetime"
read opt < "$logfile" || opt=0

update_opt () {
	param=$1
	opt=$(( (opt + param) % n ))
	opt=${opt#-}
	echo "$opt" > "$logfile"
}

case $BUTTON in
	1) update_opt 1 ;;
	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

case $opt in
	0) icon="" && text="$(date +%T)" ;;
	1) icon="" && text="$(date "+%d/%m/%Y")" ;;
esac

display_info "$STYLE" "$icon" "$text"
