#!/bin/sh

. sb-style
STYLE=5

n=3
logfile="${XDG_CACHE_HOME:-$HOME/.cache}/hardware"
read opt < "$logfile" || opt=0

update_opt () {
	param=$1
	opt=$(( (opt + param) % n ))
	opt=${opt#-}
	echo "$opt" > "$logfile"
}

case $BUTTON in
	1) update_opt 1 ;;
esac

case $opt in
    0) icon="" && text="$(sb-cpu)" ;;
    1) icon="" && text="$(sb-memory)" ;;
    2) icon="" && text="$(sb-disk)" ;;
esac

display_info "$STYLE" "$icon" "$text"
