#!/bin/sh

. sb-style
STYLE=3

icon=""
text="$(xkb-switch)"

localectl status | grep Layout | grep -q "," && display_info "$STYLE" "$icon" "$text"

notify-send -u low " Keyboard" "Changed keyboard layout to $text"
