#!/bin/sh

. sb-style
STYLE=6

fg="$(get_fg $STYLE)"
bg_icon="$(get_bg_icon $STYLE)"
bg_text="$(get_bg_text $STYLE)"

n=2
logfile="${XDG_CACHE_HOME:-$HOME/.cache}/netlog"
read rxprev txprev opt < "$logfile"

rxcurrent="$(($(cat /sys/class/net/*/statistics/rx_bytes | paste -sd '+')))"
txcurrent="$(($(cat /sys/class/net/*/statistics/tx_bytes | paste -sd '+')))"

rx=$(( rxcurrent-rxprev ))
tx=$(( txcurrent-txprev ))

update_opt () {
	param=$1
	opt=$(( (opt + param) % n ))
	opt=${opt#-}
}

case $BUTTON in
	1) update_opt 1 ;;
esac

case $opt in
    0) icon="" && text="$(( (rx)/(128) )) Kbps" ;;
    1) icon="" && text="$(( (tx)/(128) )) Kbps" ;;
esac

printf "%s%s" "$bg_icon" "$fg"
printf " %s " "$icon"
printf "%s" "$bg_text"
printf " %s " "$text"
printf "%s" "$(get_color_reset)"

echo "$rxcurrent $txcurrent $opt" > "$logfile"

case $BUTTON in
	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac
