#!/bin/sh

chosen=$(sed '/^\s*#/ d' $SCRIPTS_DIR/$1 | column -ts ';' | dmenu -i -s -l 30 -fn Monospace-14 | sed "s/ .*//")

# Exit if none chosen.
[ -z "$chosen" ] && exit

printf "$chosen" | xclip -selection clipboard
notify-send "'$chosen' copied to clipboard." &
