#!/bin/sh

get_random_wallpaper () {
	dir="$WALLPAPERS_DIR/$(ls "$WALLPAPERS_DIR" | shuf -n 1)"	
	echo "$dir/$(ls "$dir" | shuf -n 1)"	
}

create_config () {
	mon="$1"
	wallpaper="$2"

	echo -e "[xin_$mon]\nfile=$wallpaper\nmode=5\nbgcolor=#000000\n\n"
}

num_monitors="$(xrandr -q| grep "\bconnected\b" | wc -l)"
echo "" > ~/.config/nitrogen/bg-saved.cfg

mon=0
while [ "$mon" -le "$num_monitors" ]; do
	wallpaper="$(get_random_wallpaper)"
	echo "$(create_config "$mon" "$wallpaper")" >> ~/.config/nitrogen/bg-saved.cfg
	mon=$(( mon + 1 ))
done

nitrogen --restore &
