#!/bin/sh

BASEURL="https://nyaa.si"
mkdir -p "$STREAMCACHEDIR"


if [ -z "$1" ]
then
  query="$(dmenu -p "Search Torrent: " <&-)"
else
  query="$1"
fi

query="$(echo "$query" | sed 's/ /+/g')"

curl -s "$BASEURL"/?q="$query" > "$STREAMCACHEDIR"/nyaa.html

titles="$(grep -o '<a href="/view/.*</a>' "$STREAMCACHEDIR"/nyaa.html | sed 's/<[^>]*>//g')"

result_count="$(echo "$titles" | wc -l | awk '{print $1}')"
result_count=$(( result_count ))

if [ "$result_count" -lt 1 ]
then
    notify-send "😔 No Result found. Try again 🔴" -i "NONE"
    exit 1
fi

magnets="$(grep -Po 'magnet:\?xt=urn:btih:[a-zA-Z0-9]*' "$STREAMCACHEDIR"/nyaa.html)"
infos="$(grep -o '<td class=\"text-center\">.*</td>' "$STREAMCACHEDIR"/nyaa.html | sed 's/<[^>]*>//g' | xargs -n5 | awk '{print "🗄"$1" "$2"  🔻"$3"  ♻"$4" "}')"

titles_file="$STREAMCACHEDIR"/titles
echo "$titles" > "$titles_file"

infos_file="$STREAMCACHEDIR"/infos
echo "$infos" > "$infos_file"

dmenu_prompt="$(paste -d\  "$infos_file" "$titles_file")"

selected="$(echo "$dmenu_prompt" | dmenu -i -l 25)"
[ -z "$selected" ] && exit 1
selected="$(echo "$dmenu_prompt" | grep -Fn "$selected" | awk -F ":" '{print $1}')"

magnet="$(echo "$magnets" | sed "${selected}q;d")"

echo "$magnet"
