#!/bin/sh
# Dependencies - webtorrent, mpv

menu="dmenu -i -l 25"
baseurl="https://1337x.wtf"

if [ -z $1 ]; then
  query=$(dmenu -p "Search Torrent: " <&-)
else
  query=$1
fi

query="$(echo $query | sed 's/ /+/g')"

#curl -s https://1337x.to/category-search/$query/Movies/1/ > $STREAMCACHEDIR/tmp.html
curl -s $baseurl/search/$query/1/ > $STREAMCACHEDIR/tmp.html

# Get Titles
grep -o '<a href="/torrent/.*</a>' $STREAMCACHEDIR/tmp.html |
  sed 's/<[^>]*>//g' > $STREAMCACHEDIR/titles.bw

result_count=$(wc -l $STREAMCACHEDIR/titles.bw | awk '{print $1}')
if [ "$result_count" -lt 1 ]; then
  notify-send "😔 No Result found. Try again 🔴" -i "NONE"
  exit 0
fi

# Seeders and Leechers
grep -o '<td class="coll-2 seeds.*</td>\|<td class="coll-3 leeches.*</td>' $STREAMCACHEDIR/tmp.html |
  sed 's/<[^>]*>//g' | sed 'N;s/\n/ /' > $STREAMCACHEDIR/seedleech.bw

# Size
grep -o '<td class="coll-4 size.*</td>' $STREAMCACHEDIR/tmp.html |
  sed 's/<span class="seeds">.*<\/span>//g' |
  sed -e 's/<[^>]*>//g' > $STREAMCACHEDIR/size.bw

# Links
grep -E '/torrent/' $STREAMCACHEDIR/tmp.html |
  sed -E 's#.*(/torrent/.*)/">.*/#\1#' |
  sed 's/td>//g' > $STREAMCACHEDIR/links.bw

# Clearning up some data to display
sed 's/\./ /g; s/\-/ /g' $STREAMCACHEDIR/titles.bw |
  sed 's/[^A-Za-z0-9 ]//g' | tr -s " " > $STREAMCACHEDIR/tmp && mv $STREAMCACHEDIR/tmp $STREAMCACHEDIR/titles.bw

awk '{print NR " - ["$0"]"}' $STREAMCACHEDIR/size.bw > $STREAMCACHEDIR/tmp && mv $STREAMCACHEDIR/tmp $STREAMCACHEDIR/size.bw
awk '{print "[S:"$1 ", L:"$2"]" }' $STREAMCACHEDIR/seedleech.bw > $STREAMCACHEDIR/tmp && mv $STREAMCACHEDIR/tmp $STREAMCACHEDIR/seedleech.bw

# Getting the line number
LINE=$(paste -d\   $STREAMCACHEDIR/size.bw $STREAMCACHEDIR/seedleech.bw $STREAMCACHEDIR/titles.bw |
  $menu |
  cut -d\- -f1 |
  awk '{$1=$1; print}')

if [ -z "$LINE" ]; then
  notify-send "😔 No Result selected. Exiting... 🔴" -i "NONE"
  exit 0
fi
notify-send "🔍 Searching Magnet seeds 🧲" -i "NONE"
url=$(head -n $LINE $STREAMCACHEDIR/links.bw | tail -n +$LINE)
fullURL="${baseurl}${url}/"

# Requesting page for magnet link
curl -s $fullURL > $STREAMCACHEDIR/tmp.html
magnet=$(grep -Po "magnet:\?xt=urn:btih:[a-zA-Z0-9]*" $STREAMCACHEDIR/tmp.html | head -n 1) 

# Simple notification
notify-send "🎥 Enjoy Watching ☺️ " -i "NONE"

echo "$magnet"
