#!/bin/sh

login="$1"
[ -f "$login" ] || exit 1

ext="${login##*.}"

if [ "$(cd "$(dirname "$login")" && pwd)" != "$HOME/.config" ]; then
    rm "$HOME"/.config/loginscreen.*
    cp "$login" "$HOME/.config/loginscreen.$ext"
    chmod -x "$HOME/.config/loginscreen.$ext"
fi

"$HOME/.config/lightdm/update.sh"
