#!/bin/sh

ls "/sys/class/power_supply" | grep -q "BAT" || exit 1

for battery in /sys/class/power_supply/BAT?*; do
	capacity="$(cat "$battery/capacity" 2>&1)"
	battery_status="$(cat "$battery/status" 2>&1)"

	case "$battery_status" in
		"Full") status="🟩" ;;
		"Charging") status="⚡" ;;
		"Unknown") status="♻" ;;
		*) status="🔋" ;;
	esac

	[ "$capacity" -le 20 ] && [ "$battery_status" = "Discharging" ] && status="a"

	battery_info="$(printf "%s%s %d%% " "$battery_info" "$status"  "$capacity")"
done

printf "%s" "${battery_info%?}"

case $BUTTON in
	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac
