#!/bin/sh

date_str=$(date "+%d/%m/%y %T")
hour=$(date "+%H")
min=$(date "+%M")

[ $((min)) -gt 45 ] && hour="$((hour+1))"

if [ $((min)) -lt 45 ] && [ $((min)) -gt 15 ]
then
	case $hour in
		00|12) date_str="🕧 $date_str" ;;
		01|13) date_str="🕜 $date_str" ;;
		02|14) date_str="🕝 $date_str" ;;
		03|15) date_str="🕞 $date_str" ;;
		04|16) date_str="🕟 $date_str" ;;
		05|17) date_str="🕠 $date_str" ;;
		06|18) date_str="🕡 $date_str" ;;
		07|19) date_str="🕢 $date_str" ;;
		08|20) date_str="🕣 $date_str" ;;
		09|21) date_str="🕤 $date_str" ;;
		10|22) date_str="🕥 $date_str" ;;
		11|23) date_str="🕦 $date_str" ;;

	esac
else
	case $hour in
		00|12) date_str="🕛 $date_str" ;;
		01|13) date_str="🕐 $date_str" ;;
		02|14) date_str="🕑 $date_str" ;;
		03|15) date_str="🕒 $date_str" ;;
		04|16) date_str="🕓 $date_str" ;;
		05|17) date_str="🕔 $date_str" ;;
		06|18) date_str="🕕 $date_str" ;;
		07|19) date_str="🕖 $date_str" ;;
		08|20) date_str="🕗 $date_str" ;;
		09|21) date_str="🕘 $date_str" ;;
		10|22) date_str="🕙 $date_str" ;;
		11|23) date_str="🕚 $date_str" ;;
	esac
fi

echo $date_str


case $BUTTON in
	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac
