#!/bin/sh


n=2
logfile="${XDG_CACHE_HOME:-$HOME/.cache}/hardwareoption"
read opt < "$logfile" || opt=0

BUTTON=$(( BUTTON + 0 ))

update_opt () {
	param=$1
	opt=$(( (opt + param) % n ))
	opt=${opt#-}
}

case $BUTTON in
	0|1) update_opt 1 ;;
	3) update_opt -1 ;;
	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

case $opt in
	0) output="$(free --mebi | sed -n '2{p;q}' | awk '{printf (" %2.2fGiB/%2.2fGiB", ( $3 / 1024), ($2 / 1024))}')" ;; # RAM
	1) output="$(sensors | awk '/Core / {print substr($3, 2, length($3)-3)}' | sort -n | tail -1 | awk '{ printf("🌡 %.1f°C", $0) }')" ;; # CPU TEMPERATURE
esac

printf %22s "$output"

echo "$opt" > "$logfile"
