#!/bin/sh


check_started () {
	scheduled_time=$(curl -s "$1" | grep -Po "\bscheduledStartTime\"\:\"(\d+)\"" | sed 's/"//g' | awk -F':' '{print $2}')
	now_time=$(date +%s)

	[ -z "$scheduled_time" ] || [ "$now_time" -ge "$scheduled_time" ]
}

check_live () {
    printf 'location.href\nquit\n' | \
    chromium --headless --disable-gpu --disable-software-rasterizer \
    --disable-dev-shm-usage --no-sandbox --repl "$@" 2> /dev/null \
    | tr -d '>>> ' | jq -r '.result.value'
}

check_lives () {
	res=""

	while read id symbol; do
		url="https://www.youtube.com/channel/$id/live"
		redirect_url="$(check_live "$url")"

		! [ "$redirect_url" = "$url" ] && check_started "$redirect_url" && res="$(printf "%s %s" "$res" "$symbol")"
	done

	printf "%s" "$res"
}

input () {
	echo "UCoSrY_IQQVpmIRZ9Xf-y93g 🔱"
        echo "UCyl1z3jo3XHR1riLFKG5UAg 🔎"
        echo "UCL_qhgtOy0dy1Agp8vkySQg 💀"
        echo "UCHsx4Hqa-1ORjQTh9TYDhww 🐔"
        echo "UCMwGHR0BTZuLsmjY_NT5Pwg 🐙"

        echo "UC8rcEBzJSleTkf_-agPM20g 💎"

        echo "UCsUj0dszADCGbF3gNrQEuSQ 🪐"
        echo "UCO_aKKYxn4tvrqPjcTzZ6EQ 🌿"
        echo "UC3n5uGu18FoCy23ggWWp8tA 🪶 "
        echo "UCmbs8T6MWqUHP1tIQvSgKrg ⏳"
        echo "UCgmPnx-EEeOrZSg5Tiw7ZRQ 🎲"

        echo "UCKYyiJwNg2nV7hM86U5_wvw α"
}

input | awk '{print $0}' | check_lives
