#!/bin/sh


THRESHOLD=850000


check_lives () {
	res=""

	while read id symbol; do
		content_length=$(curl -Is "https://www.youtube.com/channel/$id/live" | awk '/ength/ { print $2 }' | cat -A | sed 's/\^M.*//')

		[ $content_length -gt $THRESHOLD ] && res="$(printf "%s %s" "$res" "$symbol")"
	done

	printf "%s\n" "$res"
}

input () {
	echo "UCoSrY_IQQVpmIRZ9Xf-y93g 🔱"
        echo "UCyl1z3jo3XHR1riLFKG5UAg 🔎"
        echo "UCL_qhgtOy0dy1Agp8vkySQg 💀"
        echo "UCHsx4Hqa-1ORjQTh9TYDhww 🐔"
        echo "UCMwGHR0BTZuLsmjY_NT5Pwg 🐙"

        echo "UC8rcEBzJSleTkf_-agPM20g 💎"

        echo "UCsUj0dszADCGbF3gNrQEuSQ 🪐"
        echo "UCO_aKKYxn4tvrqPjcTzZ6EQ 🌿"
        echo "UC3n5uGu18FoCy23ggWWp8tA 🪶 "
        echo "UCmbs8T6MWqUHP1tIQvSgKrg ⏳"
        echo "UCgmPnx-EEeOrZSg5Tiw7ZRQ 🎲"

        echo "UCKYyiJwNg2nV7hM86U5_wvw α"
}

input | awk '{print $0}' | check_lives
