#!/bin/sh

logfile="${XDG_CACHE_HOME:-$HOME/.cache}/netlog"
read rxprev txprev < "$logfile"

rxcurrent="$(($(cat /sys/class/net/*/statistics/rx_bytes | paste -sd '+')))"
txcurrent="$(($(cat /sys/class/net/*/statistics/tx_bytes | paste -sd '+')))"

rx=rxcurrent-rxprev
tx=txcurrent-txprev

# ! [ -z $BUTTON ] && notify-send "aeee $BUTTON"

printf "⬇ %sKbps ⬆ %sKbps\\n" \
       "$(( 8*(rx)/(1024) ))" \
       "$(( 8*(tx)/(1024) ))"

echo "$rxcurrent $txcurrent" > "$logfile"

case $BUTTON in
	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac
