#!/bin/sh

update_currency () {
	param=$1
	opt_currency=$(( (opt_currency + param) % n_currency ))
	opt_currency=${opt_currency#-}
}

update_base () {
	param=$1
	opt_base=$(( (opt_base + param) % n_base ))
	opt_base=${opt_base#-}

}

n_currency=6
n_base=4
logfile="${XDG_CACHE_HOME:-$HOME/.cache}/price"

read opt_currency opt_base < "$logfile"
BUTTON=$(( BUTTON + 0 ))

case $BUTTON in
	1) update_currency 1 ;;
	3) update_base 1 ;;
	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

symbol=""
base_symbol=""

currency=""
base=""

case $opt_currency in
	0) symbol="^v^^c#A8FF00^$^t^" && currency="usd" ;;
	1) symbol="^v^^c#E7E4D3^€^t^" && currency="eur" ;;
	2) symbol="^v^^c#F7931A^^t^" && currency="btc" ;;
	3) symbol="^v^^c#627EEA^^t^" && currency="eth" ;;
	4) symbol="^v^^c#FA6800^^t^" && currency="xmr" ;;
	5) symbol="^v^^c#F0E4B1^Ð^t^" && currency="doge" ;;
esac

case $opt_base in
	0) base_symbol="R$" && base="brl" ;;
	1) base_symbol="$" && base="usd" ;;
	2) base_symbol="€" && base="eur" ;;
	3) base_symbol="" && base="btc" ;;
esac

printf "%s %s%.2f" "$symbol" "$base_symbol" "$(curl -sf "$base.rate.sx/1$currency")"

echo "$opt_currency $opt_base" > "$logfile"
